### PR TITLE
Add ordered dict support to meteor-ejson with test

### PR DESCRIPTION
**Pull request by aphillipo**
Here you go.

### CODE REVIEW

**Comment by aphillipo** [comment]
I do not understand why PyPy is failing here on something I haven't changed?

**Comment by lyschoening** [comment]
It's a bug with the test (separate issue).

I don't want to merge the PR just yet because it is not a particularly efficient solution and also because I would want to look at decoding at the same time to make sure it works end-to-end.

**Comment by aphillipo** [comment]
Okay sure.  Decoding is going to be tricky, you probably want to default everything to dict still rather than OrderedDict but the json input always does have an order...  Maybe it's an option?

**Comment by aphillipo** [comment]
Hello there lyschoening, maybe you could explain quickly why this solution is inefficient?  I take it you would prefer appending the the OrderedDict directly instead?

The timing difference is much less than you might expect:

OrderedDict_insert.py  31.55s user 4.58s system 86% cpu 41.989 total
OrderedDict_from_list.py  36.01s user 7.61s system 89% cpu 48.764 total

So yes, it is more efficient to just insert the values but not _loads_ more efficient, probably due to OrderedDict being written in Python until version 3.5.

I wonder if you were suggesting a faster way to accomplish the same thing?

**Comment by lyschoening** [comment]
There would have been no need to construct a list at all. This here works:

```
return OrderedDict((k, _encode(v)) for k, v in o.items())
```

You would also want to check if it is a `dict` before checking if it is an `OrderedDict`. Besides that, there was also dictionary comprehension here that you missed: 

```
if any(kw in o for kw in EJSON_KEYWORDS):
    return {"$escape": {k: _encode(v) for k, v in o.items()}}
```

**Comment by aphillipo** [comment]
Ah that's very cool, will use generator expressions in the future where sensible.  I deliberately ignored the escape stuff because I won't be using it.  https://www.python.org/dev/peps/pep-0289/

**Comment by aphillipo** [comment]
OrderedDict_generator.py  34.96s user 5.06s system 86% cpu 46.388 total 

It's slower than OrderedDict insert on Python 2.7 on my machine.  Might use less memory.

Really all of the ways are the same performance wise in the real world (10 million values).

**Pull request closed without merging**
